version: "1"
services:
  discovery:
    container_name: discovery
    image: olexiybondar9685/photoapp-discovery
    build: ./PhotoAppDiscoveryService/PhotoAppDiscoveryService
    ports:
      - '8010:8010'
    depends_on:
      config-server:
        condition: service_healthy

  users-service:
    container_name: users-service
    image: olexiybondar9685/photoapp-albums
    build: ./PhotoAppApiUsers/PhotoAppApiUsers
    depends_on:
      config-server:
        condition: service_healthy

  albums-service:
    container_name: albums-service
    image: olexiybondar9685/photoapp-users
    build: ./PhotoAppApiAlbums/PhotoAppApiAlbums
    depends_on:
      config-server:
        condition: service_healthy

  api-gateway:
    container_name: api-gateway
    image: olexiybondar9685/photoapp-api-gateway
    build: ./ApiGateway/ApiGateway
    ports:
      - '8082:8082'
    depends_on:
      config-server:
        condition: service_healthy

  config-server:
    container_name: config-server
    image: olexiybondar9685/photoapp-config-server
    build: ./PhotoAppApiConfigServer/PhotoAppApiConfigServer
    healthcheck:
      test: "curl --fail --silent http://config-server:8012/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 2