version: "1"
services:
  discovery:
    build: ./PhotoAppDiscoveryService/PhotoAppDiscoveryService
    ports:
      - '8010:8010'

  users:
    build: ./PhotoAppApiUsers/PhotoAppApiUsers
    depends_on:
      - discovery