eureka.client.service-url.defaultZone=http://localhost:8010/eureka
token.expiration_time=3600000
token.secret=dgjorufhrsnjdu438fkdj38fdmcv7dm3ckvhrsnjjuwelueivhe848fhedldh5ndk
albums.url=http://ALBUMS-WS/users/%s/albums